import { Color, PieceSymbol, Square } from 'chess.js';
import { ChessMoveLinkedList } from './ChessMoveLinkedList';

export type TChessMove = {
    moveId: number;
    parent: ChessMoveLinkedList;
    variationFrom?: TChessMove;
    ravs?: ChessMoveLinkedList[];
    ply: number;
    san: string;
    beforeFen: string;
    afterFen: string;
    moveNag?: number;
    positionNag?: number;
    timeNag?: number;
    comment?: string;
    color: Color;
    from: Square;
    to: Square;
    piece: PieceSymbol;
    captured?: PieceSymbol;
    promotion?: PieceSymbol;
    isCapture: boolean;
    isPromotion: boolean;
    isEnPassant: boolean;
    isKingsideCastle: boolean;
    isQueensideCastle: boolean;
    isBigPawn: boolean;
    previousMove?: TChessMove;
    nextMove?: TChessMove;
};
